title: Theoretical Ecology
author: Bernat Guillen
email: bernatp@princeton.edu
description: >
  These are the notes of the course Theoretical Ecology given by Professor Simon Levin (Spring 2017)
baseurl: "/TheoreticalEcology"
github_username: bernatguillen
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: KaTeX
  input: GFM
